errorCorrectionDis: 60
errorMoibleAng: 1.5
errorMoibledis: 1000
strategy: {crossTime: 0.45, errorAng: 1, errorCorrectionDis: 60, errorMoibleAng: 3,
  errorMoibledis: 1000, errorRotate0: 10, errorRotate90: 92, maxVel: 10.0, minVel: 20,
  rotateSlowAng: 20, rotateYaw: 45, velYaw: 20}
vision:
  qrcode: {cannyMax: 100, cannyMin: 55, threshold: 168}
  scan_black: {middleY: 100, range: 60, scanNum: 7, sliceNum: 10, threshold: 183,
    weight: 33}
