strategy: {crossTime: 0.5, errorAng: 1.2, errorCorrectionDis: 60, errorMoibleAng: 3.0,
  errorMoibledis: 1000, errorRotate0: 0, errorRotate90: 92, maxVel: 10.0, minVel: 18,
  rotateSlowAng: 20, rotateYaw: 45, velYaw: 20}
