scan_black: {middleY: 100, range: 60, scanNum: 7, sliceNum: 10, threshold: 178, weight: 33}
strategy: {crossTime: 0.5, errorAng: 1.2, errorCorrectionDis: 600, errorMoibleAng: 3.0,
  errorMoibledis: 1000, errorRotate0: 0, errorRotate90: 90, maxVel: 10.0, minVel: 18,
  rotateSlowAng: 20, rotateYaw: 45.0, velYaw: 20}
